### ISSUE TITLE
Problems when making dataset labels

### ISSUE THREAD

**Issue by Look4-you** [chaddech/nlb#3]
Now,I'm gone to use YOLOv3. But firstly, I need to make my own dataset labels.
My question is ,is it necessary to resize my pics(it's very large 2048px ×1536px),and then to make labels at the small size of my pics. Or I can just make dataset labels on the original image(cause the YOLOv3 network will resize the pics and labels automatically or what?) .Does the operation like this will affect the finally detection result?

**Comment by chaddech** [comment]
Hey, unfortunately I'm not super familiar with YOLO so I don't know. sorry!
